# Hey Emacs, this is a -*- makefile -*-
#
include ../library/common.mk

USE_THUMB_MODE = YES

SRC = main.c $(SRCDIR)/rtc.c
SRC += $(SRCDIR)/startup_stm32f10x.c

SRC += $(CMSISDIR)/core_cm3.c
SRC += $(CMSISDIR)/system_stm32f10x.c
SRC += $(STMSPDSRCDIR)/stm32f10x_gpio.c
SRC += $(STMSPDSRCDIR)/stm32f10x_rcc.c
SRC += $(STMSPDSRCDIR)/stm32f10x_rtc.c
SRC += $(STMSPDSRCDIR)/stm32f10x_bkp.c
SRC += $(STMSPDSRCDIR)/stm32f10x_pwr.c
SRC += $(STMSPDSRCDIR)/misc.c

